### ISSUE TITLE
和DSC2015R套件整合

### ISSUE THREAD

**Issue by wush978** [dboyliao/DSC2015_RBasic#2]
由於所有課程素材最終都會整合到  [DSC2015R](https://github.com/TaiwanRUserGroup/DSC2015Tutorial/tree/master/DSC2015R)，所以需要在教學時直接帶著大家安裝所有課程

**Comment by dboyliao** [comment]
Got it~

**Comment by wush978** [comment]
我看過內容，覺得OK!
如果套件庫有問題，可透過你提供的dropbox安裝。
