### ISSUE TITLE
邏輯值的說明有學員沒聽懂

### ISSUE THREAD

**Issue by ChihChengLiang** [dboyliao/DSC2015_RBasic#8]
回頭看一下wording可能有點跳

> TRUE 跟 FALSE 是 R 的邏輯值，分別代表真與假。

建議增加多一點說明，與實際數字範例。如 1< 2 ， 1>2 這類簡單範例。

> | 請輸入 is_higher = height_101 > height_khalifa 來比較
> | 101 與哈里發塔的高度。

因為直接指派結果到變數，所以學員看到三個變數夾在兩個符號間，覺得困惑。建議少掉指派部份，只留height_101 > height_khalifa

**Comment by dboyliao** [comment]
這還好~
我會引導學員看 RStudio 的環境變數表那邊~
